# include <iostream>
# include <stdlib.h>
# include <ctime>

using namespace std;

int main() {
/*
	srand function is available in library stdlib.h
	srand is a void function meaning it doesn't return any value
	srand requires a seed value to calculate random numbers
	here we have used time() function to generate a number
	the number generated by time(NULL) is not random but it serves our purpose
*/
	srand(time(NULL));

	int num1, num2;

	// this method specifies range of random numbers between 10 and 50 
	num1 = rand() % 50 + 10;
	num2 = rand() % 50 + 10;

	// display question to the user
	cout << endl;
	cout << "   " << num1 << endl;
	cout << " + " << num2 << endl;
	cout << "________" << endl;
	cout << "   ";
	int input;
	cin >> input;

	// calculate correct answer
	int answer;
	answer = num1 + num2;

	// check if entered answer is correct
	if ( input == answer ) {
		cout << endl << "Yay! Your answer is correct." << endl;
	} else {
		cout << endl << "Your answer is incorrect. The correct answer is " << answer << "." << endl;
	}

	return 0;
}